# Generated by Django 5.2.3 on 2025-06-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigpen', '0002_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Main image for the item.', null=True, upload_to='shop/items/'),
        ),
    ]
