# Generated by Django 5.2.3 on 2025-06-28 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigpen', '0002_setup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the order', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, help_text='When the order was assigned to staff', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the order')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member assigned to work on this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Customer who placed the order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of this item in the order')),
                ('price_at_time', models.DecimalField(blank=True, decimal_places=2, help_text='Price of the item when the order was placed (for historical accuracy)', max_digits=10, null=True)),
                ('item', models.ForeignKey(help_text='The item being ordered', on_delete=django.db.models.deletion.CASCADE, to='bigpen.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='bigpen.order')),
            ],
            options={
                'unique_together': {('order', 'item')},
            },
        ),
    ]
