# Generated by Django 5.2 on 2025-04-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_listitem_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='image',
        ),
        migrations.AlterField(
            model_name='listitem',
            name='name',
            field=models.CharField(help_text='Name of the item.', max_length=255),
        ),
    ]
