# Generated by Django 5.2.3 on 2025-06-24 23:57

import django.contrib.auth.models
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('base_name', 'Full Name'), ('base_short_name', 'Short Name'), ('base_description', 'Motto / Description'), ('base_theme_color', 'Theme Color'), ('base_url', 'Website URL'), ('base_author', "Author's Name"), ('base_author_url', "Author's Website URL")], max_length=25, unique=True)),
                ('value', models.CharField(blank=True, help_text='Value for the organization detail.', max_length=255)),
            ],
            options={
                'ordering': ['ordering'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('base_logo', 'Logo'), ('base_favicon', 'Favicon'), ('base_apple_touch_icon', 'Apple touch icon'), ('base_hero_image', 'Hero / cover image')], max_length=25, unique=True)),
                ('image', models.ImageField(blank=True, help_text='\n            Upload images in recommended sizes: Logo (512x512), Favicon (32x32), Apple Touch Icon (180x180), Hero Image (2560x1440 or 1920x1080).\n            PNG format recommended for logos and icons to preserve transparency. JPG format recommended for hero.\n        ', null=True, upload_to='core/base')),
                ('description', models.TextField(editable=False)),
            ],
            options={
                'ordering': ['ordering'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order (lower numbers - zero included - appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this should be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='Custom label for this address e.g Main Office Address', max_length=100, unique=True)),
                ('building', models.CharField(blank=True, help_text='Building name or number (e.g., Britam Tower, Block A)', max_length=100)),
                ('street_address', models.CharField(blank=True, help_text='Street address including house number and street name', max_length=255)),
                ('city', models.CharField(blank=True, help_text='City name', max_length=100)),
                ('state_province', models.CharField(blank=True, help_text='State, province, or county (e.g., Vihiga County)', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='ZIP code, postal code, or equivalent', max_length=20)),
                ('country', models.CharField(blank=True, default='Kenya', help_text='Country name', max_length=100)),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps/Other map provider embed URL for displaying in iframes', max_length=500)),
                ('use_in_contact_form', models.BooleanField(default=False, help_text='Mark this as the address to use in contact forms and maps. Only one active address can be selected.')),
            ],
            options={
                'verbose_name_plural': 'Contact addresses',
                'ordering': ['order', 'label', 'city'],
            },
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order (lower numbers - zero included - appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this should be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(help_text='Email address (e.g., user@example.com)', max_length=254, unique=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as email address to be used in contact forms. If is_active is False, this will be ignored.')),
            ],
            options={
                'ordering': ['order', 'email'],
            },
        ),
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order (lower numbers - zero included - appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this should be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number (e.g., +254712345678 or 0712345678)', max_length=128, region='KE', unique=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary phone number. If is_active is False, this will be ignored.')),
                ('use_for_whatsapp', models.BooleanField(default=False, help_text='Whether this phone number should be used for WhatsApp. If is_active is False, this will be ignored.')),
            ],
            options={
                'ordering': ['order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='ContactSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order (lower numbers - zero included - appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this should be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'X (formerly Twitter)'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('snapchat', 'Snapchat'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('github', 'GitHub'), ('reddit', 'Reddit'), ('twitch', 'Twitch')], max_length=20, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon class (auto-populated based on name)', max_length=50)),
                ('url', models.URLField(help_text='URL to your selected social media profile')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ListCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order (lower numbers - zero included - appear first)')),
                ('bootstrap_icon', models.CharField(blank=True, help_text="Optional. Bootstrap icon class or path for the item. Example: 'bi bi-cart' for a shopping cart icon. Find icons at [Bootstrap Icons](https://icons.getbootstrap.com/).", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time last updated.')),
                ('name', models.CharField(help_text="Category name that groups related list items (e.g., 'Electronics', 'Furniture').", max_length=255)),
            ],
            options={
                'verbose_name_plural': 'List categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('display_name', models.CharField(blank=True, help_text='Human-readable name for this role', max_length=100)),
                ('has_portal_access', models.BooleanField(default=False, help_text='Designates whether users with this role can log into this management portal.')),
                ('is_default_role', models.BooleanField(default=False, help_text='New users will be assigned this role by default')),
                ('description', models.TextField(blank=True, help_text="Description of this role's purpose and permissions")),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order (lower numbers - zero included - appear first)')),
                ('bootstrap_icon', models.CharField(blank=True, help_text="Optional. Bootstrap icon class or path for the item. Example: 'bi bi-cart' for a shopping cart icon. Find icons at [Bootstrap Icons](https://icons.getbootstrap.com/).", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time last updated.')),
                ('name', models.CharField(help_text='Name of the item.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of this item, including features or specifications (optional).')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.listcategory')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
