# Generated by Django 5.2.1 on 2025-06-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('site_name', 'Site Name'), ('site_description', 'Site Description'), ('site_url', 'Site URL'), ('site_theme_color', 'Site Theme Color'), ('site_keywords', 'Site Keywords'), ('site_author', 'Site Author'), ('site_logo', 'Site Logo'), ('site_favicon', 'Site Favicon')], max_length=20, unique=True)),
                ('value', models.CharField(help_text='Value for the site detail (e.g., site name, description, etc.)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Detail',
                'verbose_name_plural': 'Site Details',
                'ordering': ['name'],
            },
        ),
    ]
