# Generated by Django 5.2.1 on 2025-06-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_sitedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedetail',
            name='name',
            field=models.CharField(choices=[('site_name', 'Site Name'), ('site_description', 'Site Description'), ('site_url', 'Site URL'), ('site_theme_color', 'Site Theme Color'), ('site_logo', 'Site Logo'), ('site_favicon', 'Site Favicon'), ('site_apple_touch_icon', 'Site Apple Touch Icon')], max_length=25, unique=True),
        ),
    ]
