# Generated by Django 5.2.3 on 2025-06-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Date Created (auto-filled)')),
                ('image', models.ImageField(help_text='Article Image', upload_to='blog/articles/')),
                ('title', models.CharField(help_text='Article Title', max_length=255)),
                ('content', models.TextField(blank=True, help_text='Article Content (Optional)')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category Name', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Date Created (auto-filled)')),
                ('name', models.CharField(help_text='Your name*', max_length=255)),
                ('email', models.EmailField(help_text='Your email*', max_length=254)),
                ('website', models.URLField(blank=True, help_text='Your website (Optional)')),
                ('content', models.TextField(help_text='Your Comment*')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag Name', max_length=50)),
            ],
        ),
    ]
