# Site-specific settings
SITE_URL = "https://preview.bigpen.co.ke"
SITE_NAME = "Online BigPen Kenya"
SITE_SHORT_NAME = "BigPen"
SITE_DESCRIPTION = "Delivering Stationery Supplies"
SITE_THEME_COLOR = "#ef4444"
SITE_LOGO = "/lib/static/core/img/logo.png"
SITE_FAVICON = "/lib/static/core/img/favicon.ico"
SITE_APPLE_TOUCH_ICON = "/lib/static/core/img/apple-touch-icon.png"
SITE_ANDROID_CHROME_ICON = "/lib/static/core/img/android-chrome-icon.png"
SITE_MSTILE = "/lib/static/core/img/mstile.png"
SITE_HERO = "/lib/static/core/img/hero.jpg"
SITE_MANIFEST = "/lib/static/core/manifest.webmanifest"
SITE_AUTHOR = "christianwhocodes"
SITE_AUTHOR_URL = "https://github.com/christianwhocodes/"
SITE_KEYWORDS="bigpen,Online BigPen Kenya,ecommerce,loxinformatics"