# Generated by Django 5.2.3 on 2025-06-17 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_setup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='title',
        ),
    ]
