# Generated by Django 5.2.1 on 2025-05-28 13:04

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name that groups related list items (e.g., 'Electronics', 'Furniture').", max_length=255)),
            ],
            options={
                'verbose_name_plural': 'List categories',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(help_text='Main website URL of your company, including https://.')),
                ('primary_phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Main business phone number (e.g., +254712345678).', max_length=128, region='KE')),
                ('secondary_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Alternate contact number (optional).', max_length=128, region='KE')),
                ('other_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Any other backup phone number (optional).', max_length=128, region='KE')),
                ('primary_email', models.EmailField(help_text='Primary business email address for customer or partner contact.', max_length=254)),
                ('secondary_email', models.EmailField(blank=True, help_text='Alternate email address (optional).', max_length=254)),
                ('other_email', models.EmailField(blank=True, help_text='Any other backup email (optional).', max_length=254)),
                ('building', models.CharField(blank=True, help_text='Name or number of the building where the company is located (optional).', max_length=255)),
                ('street', models.CharField(blank=True, help_text='Street or road name for the company address (optional).', max_length=255)),
                ('PO_box', models.CharField(blank=True, help_text='Postal Box address (e.g., P.O. Box 1234) (optional).', max_length=255)),
                ('city_name', models.CharField(blank=True, help_text='City or town name where the company is based (optional).', max_length=255)),
                ('zip_code', models.CharField(blank=True, help_text='Postal/ZIP code for your address (optional).', max_length=255)),
                ('map_url', models.TextField(blank=True, help_text='Google Maps embed URL for your location (Format: https://www.google.com/maps/embed?pb=...) (optional).')),
                ('twitter', models.URLField(blank=True, help_text='Link to your official Twitter/X account (optional).')),
                ('facebook', models.URLField(blank=True, help_text='Link to your official Facebook page (optional).')),
                ('instagram', models.URLField(blank=True, help_text='Link to your Instagram profile (optional).')),
                ('linkedin', models.URLField(blank=True, help_text="Link to your company's LinkedIn page (optional).")),
                ('tiktok', models.URLField(blank=True, help_text='Link to your business TikTok profile (optional).')),
                ('youtube', models.URLField(blank=True, help_text='Link to your YouTube channel (optional).')),
                ('whatsapp', models.URLField(blank=True, help_text='WhatsApp Business contact link (Format: https://wa.me/{phone_number}, e.g., https://wa.me/254712345678) (optional).')),
                ('telegram', models.URLField(blank=True, help_text='Telegram channel or group link (optional).')),
                ('snapchat', models.URLField(blank=True, help_text='Link to your Snapchat profile (optional).')),
                ('pinterest', models.URLField(blank=True, help_text='Link to your Pinterest board or profile (optional).')),
            ],
            options={
                'verbose_name': 'App organization settings',
                'verbose_name_plural': 'App organization settings',
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the item.', max_length=255)),
                ('bootstrap_icon', models.CharField(blank=True, help_text="Bootstrap icon class for this item (optional). Example: 'bi bi-cart' for a shopping cart icon. Find icons at [Bootstrap Icons](https://icons.getbootstrap.com/).", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of this item, including features or specifications (optional).')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.listcategory')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
