# Generated by Django 5.2 on 2025-05-05 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Optional. Image representing the category.', null=True, upload_to='shop/categories/')),
                ('icon', models.CharField(blank=True, help_text='Optional. Icon class or path for the category.', max_length=255)),
                ('name', models.CharField(help_text='Name of the category.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional. Description of the category.')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the item.', max_length=255)),
                ('image', models.ImageField(default='/shop/items/default_item_image.jpg', help_text='Main image for the item.', upload_to='shop/items/')),
                ('description', models.TextField(blank=True, help_text='Optional. Detailed description of the item.')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Available quantity in stock.')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured item.')),
                ('original_price', models.DecimalField(decimal_places=2, help_text='Original price of the item.', max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Optional. Discount amount to subtract from the original price.', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the item was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the item was last updated.')),
                ('category', models.ForeignKey(help_text='Category this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image for the item.', upload_to='shop/items/')),
                ('item', models.ForeignKey(help_text='Item this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='otherImages', to='shop.item')),
            ],
        ),
    ]
